### ISSUE TITLE
我为什么要工作

### ISSUE THREAD

**Issue by zhouhaibing089** [zhouhaibing089/Blog#34]
一个月前, 我在朋友圈吐槽道:

> 今天有一刻在思考: 我为什么要工作, 每天写的代码以及敲的命令对我而言到底意味着什么?
>
> April 4, 2019 7:39PM

~~一个月后, 我想我已经有一个能让自己能冷静下来的答案了.~~

~~当初发此抱怨, 有很多契机, 有很多外部因素, 也有自己内心的暗潮涌动: 当万物归于平静, 一切都变得索然无味, 一切都变得万般无奈的时候, 在每天都朝九晚七的如同行尸走肉的生活中, 你该如何慰藉自己?~~

~~在这种跳出现状审视自己的时候, 我有段时间近乎走火入魔, 我大概就是这样不停地告诉自己: 工作其实没有什么意义, 有意义的是去追寻自己所热爱的事情, 如果当下已经不再热爱了, 就不要在此浪费自己宝贵的时间了.~~

~~可是什么又是自己所热爱的呢? 你所热爱的是自己做的事情还是值得你为之热爱的环境呢? 如果我就沿着这条路继续寻根溯源, 继续探究自己想成为什么样的人, 怕是永不终止了. 所幸, 后来慢慢平静下来之后, 我醒悟到要寻解决之道还是要直面问题的核心所在: 为什么我会产生那样的感觉, 产生这种感觉的前后, 哪些外部事情发生了变更, 哪些内部认知又发生了变更.~~

---

July 20, 2019

工作就是一份交易, 雇主发的工资意味着我要尽职尽责, 除此之外, 并无太多意义所在. 从个人的角度来说, 也许我希望多学点东西, 那只不过是工作中的一些机会罢了. 一个人要开心最重要的还是要学会放下. 也许曾经抱怨环境, 但其实并没有什么太大的意义. 于公, 抱怨并不能解决问题, 不如想一想该做点什么才对得起公司支付的报酬. 于私,  抱怨于自己也无益处, 心情压抑, 无法轻松地度过工作之余, 实在无利.

**Comment by lxlxok** [comment]
稻盛和夫：真正塑造人格的并非天资和学历，而是挫折和苦难！
