### ISSUE TITLE
[WIP] 小谈CICD

### ISSUE THREAD

**Issue by zhouhaibing089** [zhouhaibing089/Blog#36]
_CI: 持续集成 (Continuous Integration)_
_CD: 持续部署 (Continuous Deployment | Continuous Delivery)_

简化来说, 软件开发周期大概分为:

1. 初始化. 比如确定是否要新建仓库(repository), 该仓库名为什么, 选用何种语言, 以及选用何种框架. 起始阶段大都先由一人设计好, 待准备好之时, 其他开发者便可开始贡献代码.
2. 添加新功能(feature). 这个时候开始接收需求, 并开始迭代开发.
3. 修复缺陷(bug). 上线之后可能或多或少会发现一些缺陷, 这个时候需要修正代码, 并重新部署上线.

取决于软件规模以及协作者数量, 这个过程可简单可复杂. 简单的时候, 通常该项目不存在协作问题, 每人都有自己独立负责的仓库或者某项子功能, 复杂的时候, 可能十几个人开发同一个功能, 其中协调难度之大可见一斑.

然积沙成塔, 任何一个有影响力的项目绝非是以一人之力铸就, 一个成功的项目必然是有各种各样的组件协同合作而成. 即便是单兵作战, 我们也应常具忧患意识, 应考虑到也许自己有朝一日要将该项目托于他人.

我想将自己近日所想分享于此, 也算自己成长的历程吧.

## 开发体验(dev experience)极为重要

俗话说磨刀不误砍柴工, 手中之刀是钝还是锋利对于生产力而言具有根本性的影响. 具体而言, 我们是否考虑:

1. **我多快能配好自己的开发环境**. 如果看到一个仓库, 我能很快地上手编译并在本机运行, 并跑通一些最基本的功能, 这将极大地激发我去hack它的兴趣, 相反, 若是由于文档不清晰, 或者配置异常复杂, 这将让我感到极度受挫并望而却步.
2. **测试框架是否易用**. 当参与一个项目当中, 如果测试框架十分完备, 并且我可以很轻易地添加一些测试样例, 这将极大鼓舞我添加测试用例的积极性. 我个人感觉人们常常不写测试用例可能是由于本身添加测试用例太过复杂. 其中最大的困难之处就是: 要跑通一个测试用例, 可能本身依赖太多.
3. **我能将项目运行在本地吗**: 有些时候, 如果整个项目的生产环境部署异常复杂, 我们常常会受挫于如何让自己的修改真实地运行但是又不影响生产环境.

## 测试第一

一个项目是否显得专业, 我通常会看:

1. README是否在开头很清楚地表达了它是个什么项目.
1. 它是否有CI的测试job. 比如pull request中的状态项数, 是否在README中有相关的badge表示它的CI build状态.
1. 如果能在README中有screenshot或者GIF展示它如何工作. 这将能很快吸引我, 并让我判断是否需要它.

因为只有这些都健全, 我才能认为该项目的owner已经准备好接收contribution了.

**Comment by lxlxok** [comment]
三天砍柴两天磨刀
